
export const multilineContinuationList = [
    { label: "At the beginning of message" },
    { label: "In the middle of message" },
    { label: "At the end of message" },
]

export const timestampPatterns = [
    { label:"Auto-Detect" },
    { label:"MM-DD-YYYY" },
    { label:"MM-DD-YY" },
    { label:"MM.DD.YYYY" },
    { label:"MM.DD.YY" },
    { label:"MM_DD_YYYY" },
    { label:"MM_DD_YY" },
    { label:"YYYY-MM-DD" },
    { label:"YYYY-MM-DDThh_mm_ss" },
    { label:"YY-MM-DD" },
    { label:"YYYYMMDD" },
    { label:"YYYYMMDD_hh" },
    { label:"YYYYMMDD_hhmmss" },
    { label:"YYMMDDhh" },
    { label:"YYMMDD" },
    { label:"YYMM" },
    { label:"DD-MM-YYYY" },
    { label:"DD-MM-YY" },
    { label:"DD.MM.YYYY" },
    { label:"DD.MM.YY" },
    { label:"DD_MM_YYYY" },
    { label:"DD_MM_YY" },
];

export const timestampFormats = [
    { label:"epoch" },
    { label:"YYYY\/MM\/DD hh:mm:ss" },
    { label:"A DD hh:mm:ss" },
    { label:"DD\/A\/YYYY hh:mm:ss" },
    { label:"DD\/A\/YYYY:hh:mm:ss" },
    { label:"A DD hh:mm:ss (YYYY)" },
    { label:"YYYY\/MM\/DD hh:mm:ss Z1" },
    { label:"A DD hh:mm:ss Z1" },
    { label:"DD\/A\/YYYY hh:mm:ss Z1" },
    { label:"DD\/A\/YYYY:hh:mm:ss Z1" },
    { label:"A DD hh:mm:ss (YYYY) Z1" },
    { label:"YYYY\/MM\/DD hh:mm:ss Z2" },
    { label:"A DD hh:mm:ss Z2" },
    { label:"DD\/A\/YYYY hh:mm:ss Z2" },
    { label:"DD\/A\/YYYY:hh:mm:ss Z2" },
    { label:"A DD hh:mm:ss (YYYY) Z2" },
    { label:"YYYY-MM-DDThh:mm:ss" },
];
